from abc import ABC, abstractmethod

class DataProvider(ABC):
    @abstractmethod
    def resolve(self, text): ...
    @abstractmethod
    def account(self, ref): ...
    @abstractmethod
    def notes(self, ref, limit): ...
    @abstractmethod
    def detail(self, note): ...
    @abstractmethod
    def products(self, ref): ...
    @abstractmethod
    def comments(self, ref): ...
